### ISSUE TITLE
Is it possible to use MTconnect to collect data of simulated CNC machine? 

### ISSUE THREAD

**Issue by RaymondCui21** [mtconnect/cppagent#112]
Hi there,

Since there is not always available to have a CNC machine on hands, so some simulation software of CNC machine is installed. I am thinking whether it is possible to install MTconnect agent to collect the simulated data via serial port on a desktop PC? Thanks.

Kind regards,

Raymond

**Comment by russwaddell** [comment]
It is feasible to collect data from a CNC simulator. However, the implementations I’m familiar with run all the simulation and data collection components (CNC sim -> MTConnect adapter for sim -> MTConnect Agent -> data collection software) on the same PC and therefore do not use serial or any other port. 

I don’t see any reason you couldn’t output to serial if you want to, though.

**Comment by MatthewPowley** [comment]
It is possible to run CNC simulation software such as Fanuc's NC Guide Pro, Siemens' Sinutrain, Okuma's PC NC Master etc... and use adapter software to collect data from them.
In the case of Fanuc it can be a pain to get Ethernet comms working and so your best bet is to use HSSB to connect the adapter to the NC (some Fanuc adapter vendors might not support this but if they do you will require '0' as the HSSB node number for NC Guide Pro).
Siemens and Okuma will also require the adapter to run locally with the simulation software due to their NC API and/or licensing restrictions.

Once you have an adapter installed you can send that traffic over Ethernet to the MTConnect agent.

**Comment by wsobel** [comment]
This is the common strategy for developing adapters. Get a simulator and hook up the adapter. It greatly depends on the control system, fanuc can use the NC Guide Pro. For HSSB it is a little harder, still the focus 2 library, but you will need to use a different connection function and the some APIs are not compatible. It’s been a while. 

For the ETHERNET comms on FANUC, you will need to get a configuration that has it enabled.  This is the tricky part and will require help unless you have one already for an existing machine. 

SIEMENS is a bit more complex since you need to license software to embed in the control or you can try OPC DA or UA depending on model. If you can enable UA, that may be a route. 

Okuma and Mazak are proprietary. There is no simulator for Mitsubishi or Fagor from what I remember. 

Heidenhain has a free simulator that can be downloaded and run. You will need to get a license for the software TNC protocol. 

(Sent from mobile)

**Comment by RaymondCui21** [comment]
> It is feasible to collect data from a CNC simulator. However, the implementations I’m familiar with run all the simulation and data collection components (CNC sim -> MTConnect adapter for sim -> MTConnect Agent -> data collection software) on the same PC and therefore do not use serial or any other port. I don’t see any reason you couldn’t output to serial if you want to, though.
> […](#)
> On May 18, 2019, at 4:48 AM, Raymond CUI ***@***.***> wrote: Hi there, Since there is not always available to have a CNC machine on hands, so some simulation software of CNC machine is installed. I thinking whether it is possible to install MTconnect agent to collect the simulated data via serial port on a desktop PC? Thanks. Kind regards, Raymond — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Thank you very much, Russ. I am using CNCSimulator Pro, do I need develop a specific MTConnect adapter for it?

**Comment by RaymondCui21** [comment]
> It is possible to run CNC simulation software such as Fanuc's NC Guide Pro, Siemens' Sinutrain, Okuma's PC NC Master etc... and use adapter software to collect data from them.
> In the case of Fanuc it can be a pain to get Ethernet comms working and so your best bet is to use HSSB to connect the adapter to the NC (some Fanuc adapter vendors might not support this but if they do you will require '0' as the HSSB node number for NC Guide Pro).
> Siemens and Okuma will also require the adapter to run locally with the simulation software due to their NC API and/or licensing restrictions.
> 
> Once you have an adapter installed you can send that traffic over Ethernet to the MTConnect agent.

Thank you very much, very clear!

**Comment by RaymondCui21** [comment]
> This is the common strategy for developing adapters. Get a simulator and hook up the adapter. It greatly depends on the control system, fanuc can use the NC Guide Pro. For HSSB it is a little harder, still the focus 2 library, but you will need to use a different connection function and the some APIs are not compatible. It’s been a while. For the ETHERNET comms on FANUC, you will need to get a configuration that has it enabled. This is the tricky part and will require help unless you have one already for an existing machine. SIEMENS is a bit more complex since you need to license software to embed in the control or you can try OPC DA or UA depending on model. If you can enable UA, that may be a route. Okuma and Mazak are proprietary. There is no simulator for Mitsubishi or Fagor from what I remember. Heidenhain has a free simulator that can be downloaded and run. You will need to get a license for the software TNC protocol. (Sent from mobile)
> […](#)
> On May 19, 2019, at 22:56, Matt Powley ***@***.***> wrote: It is possible to run CNC simulation software such as Fanuc's NC Guide Pro, Siemens' Sinutrain, Okuma's PC NC Master etc... and use adapter software to collect data from them. In the case of Fanuc it can be a pain to get Ethernet comms working and so your best bet is to use HSSB to connect the adapter to the NC (some Fanuc adapter vendors might not support this but if they do you will require '0' as the HSSB node number for NC Guide Pro). Siemens and Okuma will also require the adapter to run locally with the simulation software due to their NC API and/or licensing restrictions. Once you have an adapter installed you can send that traffic over Ethernet to the MTConnect agent. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
Thank you very much William. I thought MTConnect was specific for machine tools. So OPC-DA/UA maybe a complement of MTConnect for some CNC models, is it correct? 
Could the adapters of the same control system be compatible such as: LinuxCNC? Thank you.
