### ISSUE TITLE
Cannot show the sample of Z and cannot stream data

### ISSUE THREAD

**Issue by eddieduy** [mtconnect/cppagent#150]
1. I am working with Simulator. I try to send this request in Chrome browser: [http://127.0.0.1:5000/sample?count=20](url). The number "20" can be changed more bigger. However, I can not get the value of the Z axis. Please help me to figure out this problem. I am very new with MTConnect.
![image](https://user-images.githubusercontent.com/66301360/83506857-ea1c0580-a4f1-11ea-989c-cca1ff554a43.png)

2. How can I test the "Stream Data" function in simulation mode? When I try this request [http://127.0.0.1:5000/sample?interval=0&heartbeat=1000](url), my browser become black with the small square at the middle. Please show me how to test this function.
![image](https://user-images.githubusercontent.com/66301360/83507412-b7bed800-a4f2-11ea-95dc-d77dfd14ea92.png)

Thank you in advance.

**Comment by NeilDes** [comment]
I believe you are getting only 20 lines (oldest data in buffer) of the agent buffer that does not include an x observation. 
Browsers do not support streaming (i have not found one that supports).  If you use code, it will send data to you.

**Comment by wsobel** [comment]
To get the current values for all the data items do the following: http://127.0.0.1:5000/current <http://127.0.0.1:5000/current>

note the nextSequence in the header

Do get deltas since the nextSequence, do the following: http://127.0.0.1:5000/sample?from=<your-next-sequence>&count=20 <http://127.0.0.1:5000/sample?from=%3Cyour-next-sequence%3E&count=20>

The will give the next 20 observations after the sequence you provide for “from”. 

You can do a current at any point in the buffer as well. For example, a current at the first sequence would look something like: http://127.0.0.1:5000/current?at=92868 <http://127.0.0.1:5000/current?at=92868> 

	Of course, if data is coming in, the first sequence may no longer be available.

Best,
W
