### ISSUE TITLE
UTF-8 and other ENCODINGS?

### ISSUE THREAD

**Issue by Thichcoiphim8** [mtconnect/cppagent#151]
Hi, 
Can Agent support other encodings such as SHIFT-JIS beside the UTF-8 in the devices.xml file?

I know UTF-8 is not fully compatible with SHIFT-JIS 

If the Windows OS is using SHIFT-JIS  then it could have a problem when reading/writing the devices.xml that is using UTF-8 by default.

Thanks

**Comment by hulinning2** [comment]
Will, 
Do you know if agent can support SHIFT-JIS encoding in the devices.xml file?
Thanks

**Comment by wsobel** [comment]
Currently we are supporting utf-8 encoding. You can convert shift-jis to utf-8 with a couple of lines of script.

Not sure if it would work since we rely on the utf-8 to be nice to C++ strings and not put null terminators in the string. If I remember right, shift-jis is a unicode variant. 

Can you work with utf-8? We could see about a build for shft-jis, not sure what will break.

Best,
W

**Comment by hulinning2** [comment]
Will, 
I think we need to mention in the document of  MTConnect Agent that it can only support UTF-8 Encoding. 
This will prevent any issue when users modifies the devices.xml using different encodings.

Thanks
