### ISSUE TITLE
Fanuc Tool Offsets

### ISSUE THREAD

**Issue by tomsnell** [mtconnect/cppagent#19]
I have been requested to add tool offsets to the data collected from the machine. From what I can tell, this is not included in the adapter and therefore it can't be mapped to the agent. The Focas library has access to these variables. Has anyone else done this and give me any pointers on what to do?

**Comment by wsobel** [comment]
The adapter can pass any data to the agent, both data items and assets. Assets can be extended as can data items, so you can map something from the adapter to the agent. That being said, we are not covering offsets as you're describing in the standard at this time.

Offsets are included as deviation from nominal in the Tool model, but you need to have an existing set of measurements to determine what nominal is (it works off of tool geometries). The best way is to plug into the Cutting Tool model and offset the known measurements. You can target the functional or overall length and the maximum diameter. The actual is in the CDATA, but this assumes you know the nominal. You can also say what pot or station the tool is in and it will be referenced from the r/t data. 

Since the tool management system on FANUC controllers is rarely used, the full tool info is often OEM specific. The offsets page can be dumped, but that is a 1.4 enhancement that is in review right now. The entire concept of offsets, tool, workpiece, fixture, are being handled in the next version of the standard. We don't have a pure Offset concept in the standard at this moment. This will give the ability to track the entire offset tables for all aspects of the machining process.

As a stop gap, you could represent the current tool offset as a three space data item. Not ideal and will not trigger when adjustments are made.
