### ISSUE TITLE
ConfigTest Failing

### ISSUE THREAD

**Issue by Ghost-script** [mtconnect/cppagent#21]
I am trying to run test on Fedora 21 with gcc (GCC) 4.9.2. The Following test is failing:

Test name: ConfigTest::testMaxSize
equality assertion failed
- Expected: 15360
- Actual  : 150

Failures !!!
Run: 201   Failure total: 1   Failures: 1   Errors: 0

**Comment by wsobel** [comment]
this tests the logger file max size. it's a simple string parser, should not fail. 

debug the test.

- W

**Comment by Ghost-script** [comment]
I tried debugging. Seems like the `mConfig->loadConfig(logger)` is not loading the config properly or having trouble flushing the old value. I tried changing the `istringstream logger("logger_config {"max_size = 150\n"}\n");`  **max_size** value. Despite different consecutive sizes of 15K , 15M , 15G It always tested with the first value set as max_size. So **max_size** is always **150**.

**Comment by wsobel** [comment]
This is because of some experimental code I just added to monitor the config files and do a warm start if they change. I do not roll the logger on a warm start. This has nothing to do with fedora. 

Change the test to create a new config object for each test. This will fix the issue. 

This was a quick test I put in for a user to support auto agent configuration.

**Comment by wsobel** [comment]
Fixed test and recreated agent configuration object each time.
