### ISSUE TITLE
Error when building Makfile with cmake on Ubunthu 20.04 in V2.0 of the cppagent

### ISSUE THREAD

**Issue by rwuthric** [mtconnect/cppagent#221]
When installing the cppagent on Ubuntu 20.04 LTS on April 24 2022 (Version 1.7) following the instructions here https://mtcup.org/Installing_C++_Agent_on_Ubuntu all went perfectly

I tried to install it on another Ubuntu 20.04 machine on May 28 2022 (Version 2.0) following same procedure but this time CMake was unable to complete and ends with the error

CMake Error at CMakeLists.txt:76 (conan_basic_setup):
  Unknown CMake command "conan_basic_setup".

I tried on a fresh Ubuntu 20.04 LTS machine and faced same error

I tried as well on the machine I was successfully able to install cppagent on April 24 and same error pops up when using the latest code (Version 2.0) from github  (whereas if I use the cloned git from April 28 [Version 1,7] everything works fine)

What I am missing to make it work with the newest code from github?

**Comment by wsobel** [comment]
The build process has changed since we have switched to conan for the build process.

See the build instructions: [Building on Ubuntu 20.04](https://github.com/mtconnect/cppagent#building-on-ubuntu-on-2004-lts)

If you still have issues, I can help sort them out. I am in the process of updating the README.

**Comment by wsobel** [comment]
Not hearing anything back, I assume the new instructions work.
