### ISSUE TITLE
Version v2.1.0.1 - cppagent-v2.1.0.1-win32 - still cannot support Windows XP x86

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#271]
Will, 
Could you build to support Windows XP SP3 x86?

Thanks

**Comment by wsobel** [comment]
I have been working on this for a day with no luck. I have been making changes to try to support the oddities of VS 2019 and the v141_xp toolchain, but the compiler is crashing on the following line:

```
1>c:\.conan\eac2a218\1\include\boost\beast\http\impl\serializer.hpp(284): fatal error C1001: An internal error has occurred in the compiler.
```

I'm not sure if there are any quick fixes. The XP toolchain is no longer officially supported, and there are a lot of issues with the build. I'm wondering if there may be another compiler or way to solve this. I think we may just need to stay with the old agent (C++ 11) for XP since I have not found any other build systems supporting XP at this time.

I may try a fallback to MinGW and see if they have an old toolchain and a newish gcc compiler that will work. 

But, for now, I am stuck. The platform has been officially orphaned and there is little to no information on how to work around these issues. Microsoft has a simple response, we no longer support XP, good luck!

Best,
W

**Comment by hulinning2** [comment]
I think VS2019 does work well with XP I normally use VS2010 if you could try VS2010 
Thanks

**Comment by MatthewPowley** [comment]
Windows XP support in VS2019 is limited to C++ 11.
It requires that all binaries and supporting libraries are also compiled with this compiler. This may not be possible to do with the Conan package management system.
Some of the third party libraries (as well as the agent) may have moved their minimum C++ level to C++14/17, so it is extremely unlikely to support this platform going forward.
Equipment with Windows XP should be considered obsolete. I know that lots of people who own expensive CNC won't want to hear this but the OEM should provide a MTConnect adapter for the XP platform in this case but the MTConnect Agent simply runs on another supported device.

**Comment by hulinning2** [comment]
I think that is what I plan to do if new version of Agent cannot support XP.  Our adapter still can run on XP and sends out stream with MTConnect spec 2.0 or newer specs.  Newer MTConnect Agent must be installed on remote PC using Windows 7 or 10 to be able to support MTConnect 2.0.  Is the current document of MTConnect Agent mentioned that it cannot support XP?  I think this is important information for developers, OEM, and end users.  Thanks

**Comment by wsobel** [comment]
I can cross-compile all the dependencies with conan; it does a nice job building for any target architecture. The issue I had was when we specified the C++ 17 language spec and VS 2019 (have not tried 2020), and I use the v141_xp toolchain (the last to support XP), the compiler crashed. The crash is somewhere in the beast HTTP session support, which is a header-only meta-programming masterpiece that requires a lot of C++ language support. I tried to work around some of the issues, like C++ 17 being specified as the target ISO language spec, but the v141 toolchain not supporting C++ 17. The lack of support in the headers makes my head hurt, need to work around a bunch of missing or incorrect namespaces.

I think splitting the agent out when supporting XP is correct. It is hard to support a platform that MS has ceased to support. The last flailing attempt I was going to make was to see if I could cross-compile on mingw-32 and see if using GCC 10 and the core libs instead of all the runtime stuff I could get it to work. Seems like a longshot, but I'll give it a go.

This will require building the entire ming32 toolchain to target XP or finding one that exists. Not a today thing.
