### ISSUE TITLE
Build fails on 32-bit ARM systems

### ISSUE THREAD

**Issue by dcaputo-harmoni** [mtconnect/cppagent#286]
Ever since [this commit](https://github.com/mtconnect/cppagent/commit/ec88ae2146ad6f2c1998d9ba2b6761d70a713dfe) builds fail on 32-bit ARM systems with the following errors:
```
/usr/bin/ld: ../lib/libagent_lib.so: undefined reference to `__atomic_is_lock_free'
/usr/bin/ld: ../lib/libagent_lib.so: undefined reference to `__atomic_fetch_or_8'
/usr/bin/ld: ../lib/libagent_lib.so: undefined reference to `__atomic_load_8'
collect2: error: ld returned 1 exit status
```
This is a known openssl issue per [here](https://github.com/openssl/openssl/issues/16551) among other sources (google openssl atomic arm). I managed to fix this with a simple change to agent_lib/CMakeLists.txt to instruct it to link with `-latomic` :
```
sed -i "s/openssl/openssl atomic/g" cppagent/agent_lib/CMakeLists.txt
```
Submitting here for consideration.

**Comment by wsobel** [comment]
Please give the following:Operating systemCompiler version Toolchain if anyThanksW(Sent from mobile)On Mar 31, 2023, at 19:05, dcaputo-harmoni ***@***.***> wrote:﻿
Ever since this commit builds fail on 32-bit ARM systems with the following errors:
/usr/bin/ld: ../lib/libagent_lib.so: undefined reference to `__atomic_is_lock_free'
/usr/bin/ld: ../lib/libagent_lib.so: undefined reference to `__atomic_fetch_or_8'
/usr/bin/ld: ../lib/libagent_lib.so: undefined reference to `__atomic_load_8'
collect2: error: ld returned 1 exit status

This is a known openssl issue per here among other sources (google openssl atomic arm). I managed to fix this with a simple change to agent_lib/CMakeLists.txt to instruct it to link with -latomic :
sed -i "s/openssl/openssl atomic/g" cppagent/agent_lib/CMakeLists.txt

Submitting here for consideration.

**Comment by dcaputo-harmoni** [comment]
Operating System: Debian Bullseye
Compiler Version: Stock build-essentials & cmake included with Debian Bullseye
Toolchain: Not applicable

Note that this is all being done in a docker container and I followed the build instructions from the Dockerfile included in the root folder of cppagent (except using Debian Bullseye image instead of Ubuntu 22.04)

**Comment by wsobel** [comment]
I’ll check it out. Sometimes there are subtle differences in the system libs and this is helpful to reproduce. I don’t want to break the build on other platforms when changing the dependencies. (Sent from mobile)On Apr 1, 2023, at 04:41, dcaputo-harmoni ***@***.***> wrote:﻿
Operating System: Debian Bullseye
Compiler Version: Stock build-essentials & cmake included with Debian Bullseye
Toolchain: Not applicable
Note that this is all being done in a docker container and I followed the build instructions from the Dockerfile included in the root folder of cppagent (except using Debian Bullseye image instead of Ubuntu 22.04)

Please give the following:Operating systemCompiler version Toolchain if anyThanksW(Sent from mobile)On Mar 31, 2023, at 19:05, dcaputo-harmoni @.***> wrote:﻿
Ever since this commit builds fail on 32-bit ARM systems with the following errors:
/usr/bin/ld: ../lib/libagent_lib.so: undefined reference to __atomic_is_lock_free' /usr/bin/ld: ../lib/libagent_lib.so: undefined reference to __atomic_fetch_or_8'
/usr/bin/ld: ../lib/libagent_lib.so: undefined reference to `__atomic_load_8'
collect2: error: ld returned 1 exit status
This is a known openssl issue per here among other sources (google openssl atomic arm). I managed to fix this with a simple change to agent_lib/CMakeLists.txt to instruct it to link with -latomic :
sed -i "s/openssl/openssl atomic/g" cppagent/agent_lib/CMakeLists.txt
Submitting here for consideration.

**Comment by dcaputo-harmoni** [comment]
Thank you. And just FYI as you evaluate the best course of action, this has come up at the cmake level [here](https://gitlab.kitware.com/cmake/cmake/-/issues/21174) and it was determined that while not necessarily problematic to automatically link to atomic for non-32-bit-ARM architectures, it is up to the application to make this determination. So I believe others are simply evaluating the architecture and adding in `-latomic` for those who need it.
