### ISSUE TITLE
Format of agent.cfg file

### ISSUE THREAD

**Issue by scottmwyant** [mtconnect/cppagent#326]
I'm not a cpp developer so if this comes off as uninformed, it's because that's exactly true.

The format of the agent.cfg file has always seemed odd to me.  I've seen the docs mention "BOOST config file format".  A quick search leads me to https://www.boost.org/, but I haven't found a reference on the file format and haven't seen this format used "in the wild" anywhere but in this project.  I assume this format is commonly used in C++ projects?  At quick glance it looks like JSON, but it's clearly not.  Might remove some friction for new users if it were JSON or YAML.

I suppose this issue may help gage how much the community cares about the format of `agent.cfg`.  If I'm alone here I can adapt :)

**Comment by wsobel** [comment]
We can support JSON, just haven't added or documented since I haven't got around to it. 

The format is based on the C++: [dlib](http://dlib.net)'s [config_reader_kernel](http://dlib.net/dlib/config_reader/config_reader_kernel_abstract.h.html) parser. We switched to boost to use boost beast and tools. At the time we started in 2008, it was not clear if boost or dlib was going to prevail. 

I wrote config parser to take the old dlib format and turn it into property trees in boost. This means we *could* easily switch to json or xml for configuration. I would suggest json since xml is a pain for config. If public sentiment was strong enough we could also support yaml. 

It could be easily done but would need to be tested to make sure it was doing the right thing. If you would like to test, I can test out the boost json parser?

**Comment by scottmwyant** [comment]
@wsobel yes, I would be happy to help test/validate.  I agree JSON would be the best choice.

**Comment by robot-ranger** [comment]
yes to json agent config!

**Comment by MRIIOT** [comment]
Would it look like this?


```json
{
  "Devices": "./devices.xml",
  "AllowPut": true,
  "ReconnectInterval": 1000,
  "BufferSize": 17,
  "SchemaVersion": 2,
  "MonitorConfigFiles": true,
  "Pretty": true,
  "ConversionRequired": true,
  "MinimumConfigReloadAge": 30,
  "ShdrVersion": 2,
  "Sinks": {
    "Mqtt2Service": {
      "MqttHost": "wss.sharc.tech",
      "MqttPort": 1883,
      "MqttClientId": "ox003_sink2",
      "AssetTopic": "MTConnect/Asset/[device]",
      "CurrentTopic": "MTConnect/Current/[device]",
      "ProbeTopic": "MTConnect/Probe/[device]",
      "SampleTopic": "MTConnect/Sample/[device]",
      "MqttLastWillTopic": "MTConnect/Probe/[device]/Availability",
      "MqttCurrentInterval": 10000,
      "MqttSampleInterval": 500,
      "MqttSampleCount": 1000
    }
  },
  "Adapters": {
    "HCN001": {
      "Url": "http://mtconnect.mazakcorp.com:5719",
      "SourceDevice": "HCN001"
    },
    "48e7290b1184": {
      "Protocol": "mqtt",
      "MqttHost": "wss.sharc.tech",
      "MqttPort": 1883,
      "MqttClientId": "ox003_sharc_48e7290b1184",
      "Topics": "mtc/ingest/48e7290b1184"
    }
  },
  "Files": {
    "schemas": {
      "Path": "/mtconnect/data/schemas",
      "Location": "/schemas/"
    },
    "styles": {
      "Path": "/mtconnect/data/styles",
      "Location": "/styles/"
    },
    "Favicon": {
      "Path": "/mtconnect/data/styles/favicon.ico",
      "Location": "/favicon.ico"
    }
  },
  "DevicesStyle": {
    "Location": "/styles/styles.xsl"
  },
  "StreamsStyle": {
    "Location": "/styles/styles.xsl"
  },
  "logger_config": {
    "logging_level": "debug"
  }
}
```

**Comment by wsobel** [comment]
Yes. Make sure the file extension is `.json`
