### ISSUE TITLE
build-docker-image.yml fails - dockerfile path

### ISSUE THREAD

**Issue by robot-ranger** [mtconnect/cppagent#328]
looks like docker files were refreshed and organized into /docker, but build-docker-image-yml was not updated.

`Error: buildx failed with: ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory`

seems like a trivial fix. i will setup a PR.

**Comment by wsobel** [comment]
I did not update the automatic build since we need to have a discussion regarding which image we want to register with docker hub as the default mtconnect image. I have created some variants, but the demo only makes sense in certain situations. I think something that provides external configuration options using volumes would be best. What do you think?(Sent from mobile)On Sep 24, 2023, at 18:38, robot-ranger ***@***.***> wrote:﻿
looks like docker files were refreshed and organized into /docker, but build-docker-image-yml was not updated.
Error: buildx failed with: ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory
seems like a trivial fix. i will setup a PR.

**Comment by robot-ranger** [comment]
i like the idea of a default, reference, agent image. we would certainly use it. personally, we dont have much preference on base OS. assuming the functionality and performance is similar, I would prefer the smaller image size with alpine.

i was going to setup build-docker-image.yml to use a repository configuration variable `DOCKERFILE_PATH` or similar. this would allow per-repo configuration, but that is from my perspective, pushing to my own images to my hub acct. I have been maintaining my own fork really just to build docker images in the absence of standard/default image availability.

**Comment by robot-ranger** [comment]
i do appreciate the volumes approach. makes applying our own configs very easy

**Comment by robot-ranger** [comment]
here is what i was thinking:

https://github.com/robot-ranger/cppagent/commit/e9845054943c4fe0b5ecc4a508258270d9983c46

**Comment by wsobel** [comment]
That would work. I'll get to this once I finish a few other items.

**Comment by wsobel** [comment]
I did something similar so we can do multiple builds. I used a matrix build and use include instead of env variables. See what you think
