### ISSUE TITLE
docker tag `2.2.0.16` is actually agent v2.2.0.15

### ISSUE THREAD

**Issue by robot-ranger** [mtconnect/cppagent#386]
docker image:
![image](https://github.com/mtconnect/cppagent/assets/93950632/a24c2552-ae80-4235-96a8-840fc51e1d84)

agent page:
![image](https://github.com/mtconnect/cppagent/assets/93950632/d2d7a66a-0588-4e0c-96f2-ff4f05fbf0bb)

...I also do not have any LWT message at `MTConnect/Probe/Agent.{UUID}/Availability`, but i assume that is just because tag `2.2.0.16` is actually agent `2.2.0.15`:
![image](https://github.com/mtconnect/cppagent/assets/93950632/c6d67074-a357-44b4-8c88-ae72b298cddc)

**Comment by wsobel** [comment]
That’s very odd. The version tagging is automatically created when I tag a version for release. I’ll make sure the version in cmake match. ThanksW(Sent from mobile)On Dec 22, 2023, at 02:28, robot-ranger ***@***.***> wrote:﻿
docker image:
image.png (view on web)
agent page:
image.png (view on web)
...I also do not have any LWT message at MTConnect/Probe/Agent.{UUID}/Availability, but i assume that is just because tag 2.2.0.16 is actually agent 2.2.0.15:
image.png (view on web)

**Comment by robot-ranger** [comment]
ya, looking at https://github.com/mtconnect/cppagent/blob/main/.github/workflows/build-docker-image.yml,

the only thing i can see at the surface is that the env vars must be mixed up somehow

**Comment by wsobel** [comment]
Reporting correct version now.

**Comment by wsobel** [comment]
I will close this if we cannot reporduce.

**Comment by robot-ranger** [comment]
yes, sorry im late to this. I see 2.3.0.2 now (which was latest last I pulled). seems good now.
