### ISSUE TITLE
Data items reported at the same time stamp?

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#40]
I have seen that data items reported at the same time stamp however agent will send out each data item in different sequence number with the same time stamp. 
Because related data items are reported in different sequence numbers it is possible that an application will miss interpret data due to this.
Ex: Spindle Surface speed and Mode
An application might get the spindle surface speed but not mode at the same time due to different sequence number.  As a result the application might think the spindle surface speed is in the current mode but it is actually already changed.  

Is this an issue?

Thanks

**Comment by PatrickRitchie** [comment]
It would be useful if the standard provided the ability to query an agent by timestamp instead of just by sequence number in order to prevent situations like @hulinning2 described. Although most applications that continually collect data use a previous Current request in order to get the next available data to use for the subsequent Sample request, this would make it easier for more simple applications that for instance just graph a DataItem over a period of time. Below is an example:

### Example sample request:

_/sample?path=//DataItem[@type="EXECUTION"]&from=2016-11-04T08:00:00Z&to=2016-11-04T09:00:00Z_

This would return all of the Execution data for the specified timespan (1 hour) and could easily be used to diagnose issues that happened within that hour of operation instead of trying to figure out the range of sequence numbers that this timespan would correspond to.

### Example use case:

I started working on a [XML stylesheet](https://github.com/TrakHound/MTConnect-Agent-Stylesheet) for this MTConnect Agent which is based on Bootstrap. Since Bootstrap uses jQuery already, it would be easy to integrate a simple javascript graphing tool to show DataItem changes over a period of time. Since this would not be continually running the Current->Sample sequence, it would be difficult to figure out what sequence numbers correspond to a desired time range though it would be easy to query the agent based on the time range itself if this feature was available.

**Comment by wsobel** [comment]
The standard assigns sequence numbers in the order the data arrives. The timestamps are not part of the protocol and can be set by the adapter. We currently do not support query by timestamp our reordering of events based on time. 

If you are not a member of the MTConnect TAG, I would suggest joining and then posting this comment to the group as a change to the standard. We will need to review and understand how this will change the requirements for streaming data delivery. Will we be required to add a delay to make sure no new data was arriving. There are some details that would need to be discussed.  This can be posted to the MTConnect projects web site if you're a member. 

Thanks
Will
